AWSTemplateFormatVersion: "2010-09-09"
Description: Cloudformation to build ec2 instances
Parameters:
  VpcName:
    Type: String
    Description: VPC Name
    Default: ''
  ImageId:
    Type: String
    Description: AMI ID to use
    Default: ''  # Linux/Unix AMI
  Subnet:
    Type: String
    Description: Default subnet to use
    Default: ''
  InstanceType:
    Type: String
    Description: ec2 instance type
    Default: ''
  SecurityGroups:
    Type: String
    Description: SG
    Default: ''

Resources:
  LinuxServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      KeyName: us-east-1keypair
      InstanceType: !Ref InstanceType
      SecurityGroupIds: 
        - !Ref SecurityGroups
      SubnetId: !Ref Subnet
      BlockDeviceMappings:  
        -
          DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp3
            DeleteOnTermination: true
            VolumeSize: 8
      Volumes:
        - Device: /dev/xvdf
          VolumeId: !Ref AddVolume
      Tags:
        - Key: Name
          Value: Linux Server
  
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref LinuxServer

  AddVolume:
    Type: AWS::EC2::Volume
    Description: Additional EBS Volume
    Properties:
      AvailabilityZone: us-east-1b
      VolumeType: gp2
      Size: 5
      Encrypted: true


